name: news_app_clean_architecture
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  win32: ^5.5.0

  cupertino_icons: ^1.0.2

  #icon
  ionicons: ^0.1.2

  #state management
  flutter_bloc: ^8.1.2

  #comparing dart objects
  equatable: ^2.0.5

  #service locator
  get_it: ^7.7.0

  #dateFormat
  intl: ^0.19.0

  #Database
  floor: ^1.5.0

  #make request to api
  retrofit: ^4.1.0

  # Firebase
  firebase_core: ^2.24.0
  cloud_firestore: ^4.13.3
  firebase_storage: ^11.5.5

  # Gallery
  image_picker: ^1.2.1

  #Hooks
  flutter_hooks: ^0.20.5

  #chached image 
  cached_network_image: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  retrofit_generator: ^8.1.0
  floor_generator: ^1.5.0
  build_runner: ^2.4.9
  

flutter:

  uses-material-design: true

 
  fonts:
    - family: Muli
      fonts:
        - asset: assets/fonts/muli/Muli.ttf
        - asset: assets/fonts/muli/Muli-Bold.ttf
          weight: 700
        - asset: assets/fonts/muli/Muli-Light.ttf
          weight: 300
